language: python
arch:
  - amd64
  - ppc64le
sudo: false

matrix:
  fast_finish: true
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6

# command to install dependencies
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install pytest
  - pip install mock

# command to run tests, e.g. python setup.py test
script:
  - py.test -v -x --doctest-modules --pyargs datashape -rsX --tb=short

notifications:
  email: false
  flowdock: b08b3ba4fb86fa48121e90b5f67ccb75
  on_success: "change"
  on_failure: "always"

